### DISCUSSION TITLE
Is there a way to disable replying in the COMMENT widget?

### DISCUSSION THREAD

**Discussion by jimsafley** [annotorious/annotorious#404] [Q&A] [answered]
In v2.7.13, can I configure the COMMENT widget to disable replying? I would like the widget to allow only one comment.

**Comment by rsimon** [comment, marked as answer]
Hi, I'm afraid that's not currently implemented. You could hack your way through CSS, I guess. I think there are distinct CSS classes to the reply section. You could hide it by setting it to `display: none`.

**Reply by jimsafley** [reply]
Thanks. I can simulate this behavior using CSS:

```css
div.r6o-widget.comment:nth-of-type(n+2) {
    display: none;
}
```
